name: Build performance test docker image
description: Prepare build environment for Performance tests

runs:
  using: "composite"

  steps:
  - name: Checkout
    uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    with:
      persist-credentials: false
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
  - name: Build and push
    uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
    with:
      context: .
      file: ./tests/performance/Dockerfile
      tags: performance_tests:latest
      outputs: type=docker,dest=/tmp/performance_tests.tar
  - name: Upload artifact
    uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
    with:
      name: performance_tests
      path: /tmp/performance_tests.tar
